apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-deployment
  namespace: {{ .Name }}
spec:
  params:
  - name: app-name
    description: the application name
  - name: app-template
    description: the application template to create objects from
  - name: build-type
    type: string
    description: "Selected build type: quarkus-jvm, quarkus-fast-jar, quarkus-native, spring-boot"
  - name: git-repo
    type: string
    description: "Git Repository SSH URL"
  - name: git-branch
    type: string
    description: "Git Branch to clone"
    default: "main"
  - name: config-git-repo
    type: string
    description: "Git Repository URL"
  - name: config-git-branch
    type: string
    description: "Git Branch to clone"
    default: "main"
  - name: config-git-path
    type: string
    description: "Config Path"
    default: "/"
  steps:
  - name: rollout
    image: image-registry.openshift-image-registry.svc:5000/openshift/origin-cli:latest
    imagePullPolicy: IfNotPresent
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
    - |-
        echo -----------------------------------
        echo Creating objects from template: $(params.app-template)
        oc process openshift//$(params.app-template) -p APP_NAME=$(params.app-name) -p GIT_REPOSITORY=$(params.git-repo) -p GIT_BRANCH=$(params.git-branch) -p CONFIG_GIT_REPOSITORY=$(params.config-git-repo) -p CONFIG_GIT_BRANCH=$(params.config-git-branch) -p CONFIG_GIT_PATH=$(params.config-git-path) | oc apply -f -
        echo -----------------------------------
